### PR TITLE
Skylab Readme Update

### PR DESCRIPTION
**Pull request by kbergin**
I've updated the skylab readme a little bit. The template readme is in the wiki https://github.com/HumanCellAtlas/skylab/wiki/Template-Pipeline-Readme

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
This looks good to me. 

The only thing I could think to add would be a note to include versioning and source for the genome index and annotation used. Although this is defined within the associated reference wdl, it could be nice to have it upfront. 

Counter-argument to this suggestion would be that it would be one more location containing metadata that would need to be updated if the reference changes.

**Comment by kbergin** [comment]
@ambrosejcarr , was your comment in regards to the Analysis Pipeline template readme in the wiki (linked above), or the skylab readme changes in the attached PR? The information about the reference used in the WDL is in the template linked above, here: https://github.com/HumanCellAtlas/skylab/wiki/Template-Pipeline-Readme#genome-reference

Someday when our references are stored in the blue box it may also be handy to list the specific UUID:Version of the bundle we are using for our pipeline.

**Comment by kbergin** [comment]
I've added to the template to explicity state to include versions

**Comment by ambrosejcarr** [comment]
@kbergin You are correct, I need more coffee; I reviewed the template readme (it's good!). 

Generally, I like this readme as well. 

One concern I have is that I am not sure, given this README, that I would be able to run the smartseq2 pipeline. 

Part of that is the links to external documentation in lieu of instructions, which could be a bit frightening to the uninitiated. Since it's relatively simple, If I was a user I would love to have an example with full commands to run the pipeline on either (1) google compute or (2, probably better) local, using specific examples (wdl, json, and toy data) from the smartseq2 pipeline. It'd be the hello-world for our pipelines, and users could feel good about being able to just download and run it. 

Then the documentation links could serve as a reference for users who might want to dig in and play around with the internals.

**Comment by kbergin** [comment]
@ambrosejcarr That's a good plan, I agree it'd be useful for the user to easily be able to run our pipelines. Let me think through this some more

**Comment by kbergin** [comment]
In the current version of the readme I've stated the way to run is a "for now" because I'm thinking the easiest way for someone to try our pipeline may be to eventually have a public firecloud workspace with the example and some example data for someone to try it out or clone it to their own firecloud space and play with it on their data.. Once our pipeline is blessed and in the public methods repos.

**Comment by ambrosejcarr** [comment]
Yea, it's not a trivial thing to incorporate. I'd advocate merging the changes in this PR with an additional todo for later regarding the run instructions.

**Comment by kbergin** [comment]
Yes, I was thinking at least some more info and some lists of TODOs would be, at the least, a step forward compared to the initial readme we made. 

I'll add a TODO to improve instructions on running our pipelines

**Comment by kbergin** [comment]
Back to you @ambrosejcarr

**Pull request merged**
