### PR TITLE
[RFC] upload optimus report in restructured text

### PR DESCRIPTION
**Pull request by ambrosejcarr**
### Purpose

Make it possible to check in the Optimus Benchmarking Report. We can discuss if we want to check this in, or if we'd prefer not to. If we want to, here's how we can do it. 

To reproduce: 

1. Download the report as `.docx` from the google doc
2. Install `pandoc`, type the following code: 
```bash
# convert the file
pandoc -f docx Optimus\ Acceptance\ Report.docx -t rst -o optimus_report.rst
# get the media (image) files from the .docx file
unzip ./Optimus\ Acceptance\ Report.docx 
mv ./word/media media 
```

### Review Instructions

Click the `.rst` file in the bottom of the review to render the file and look at the output for errors. I made a quick check and it seems the only thing `pandoc` did that might not be desirable is that it put the numbers for the table of contents on the wrong side of the headings (right side).

Link for easy review: https://github.com/HumanCellAtlas/skylab/blob/1cd2beff75af8d0e9bf34aaefaeb19f9c9829b77/benchmarking/optimus/optimus_report.rst

### PR Checklist
_Please ensure the following when opening a PR:_

- [ ] This PR added or updated tests.
- [X] This PR updated docstrings or documentation.
- [X] Let Jodi (**jodihir**) know when there is user-facing documentation updates needed!
- [ ] This PR applied the Mint style guide for WDL.
- [ ] This PR has no WDL linting errors reported by [miniwdl](https://github.com/chanzuckerberg/miniwdl)
- [ ] This PR considered generalizability beyond our own use case.

---
### Follow-up Discussions
_Please append follow-up discussions and issues during the review process below:_

- No follow-up discussions.

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
cc @jodihir in case interested in `docx -> .md/.rst` conversion.

**Comment by barkasn** [comment]
@ambrosejcarr Can we add the instructions for generating the document next to it so that can be reproduced in the future? Otherwise I can approve this.

**Comment by ambrosejcarr** [comment]
@barkasn Done.

**Comment by barkasn** [comment]
retest this please

**Comment by barkasn** [comment]
I'm going to merge this by overriding the tests as there are no code changes and the tests fail due to changes in dependencies since this branch was created.

**Pull request merged**
