### PR TITLE
Fix Task Names

### PR DESCRIPTION
**Pull request by barkasn**
### Purpose
- Fix the task names for Optimus
- Addressing issue GL-192

---
### Changes
_Please list out what major changes were made in this PR to address the issue:_

- Renaming of MarkDuplicates.wdl to UmiCorrection.wdl
- Changes to the UmiCorrection Task name
- Change the name of the postUMI sort step to preMergeSort

---
### Review Instructions
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_
- Run the pipeline to confirm that it works for you (I did that already)
- Check that the output checksums of the Pipeline match what was previously generated

### CODE REVIEW

**Comment by barkasn** [comment]
@rexwangcc I've update the figure now. This does indeed change dependency names.

**Comment by barkasn** [comment]
retest this please

**Comment by rexwangcc** [comment]
retest this please

**Comment by barkasn** [comment]
retest this please

**Comment by rexwangcc** [comment]
@barkasn The test timed out after 1hr but the underlying workflow succeeded after 2 hrs: https://job-manager.mint-dev.broadinstitute.org/jobs/53eafd79-195d-4107-9ba4-0acc8fc12dfc Feel free to merge this PR!

**Comment by barkasn** [comment]
retest this please

**Comment by rexwangcc** [comment]
Per offline discussion with @barkasn , forcefully merging this PR since all workflows are passing. The failing tests are due to timeout limits of the test suite itself. QA should only check if https://job-manager.mint-dev.broadinstitute.org/jobs/53eafd79-195d-4107-9ba4-0acc8fc12dfc passed or not.

**Pull request merged**
