### PR TITLE
Add version parameter to all of the analysis pipelines except the deprecated 10x.

### PR DESCRIPTION
**Pull request by rexwangcc**
I expect this PR should wait for @jishuxu's PR about outputs changes to be merged in so we can tag them together as `smartseq2_v2.0.0`

Please ensure the following when opening a PR:
- [ ] Added or updated tests
- [ ] Updated documentation
- [ ] Applied style guidelines
- [ ] Considered generalizability beyond our own use case

### CODE REVIEW

**Comment by samanehsan** [comment]
I just saw that the circleci tests are failing, could you take a look at those in case they need to be updated as well?

**Comment by rexwangcc** [comment]
@samanehsan Yeah, I have no idea why the portability tests failed, consulting @mckinsel now, the worst case would be that adding a version to the pipelines is destroying the portability :(

**Comment by rexwangcc** [comment]
The latest failed Mintegration test was because that the test suite itself is not updated to match the master branch of Lira.

**Comment by rexwangcc** [comment]
retest this please

**Pull request merged**
