### PR TITLE
Ck filter cells

### PR DESCRIPTION
**Pull request by barkasn**
## Purpose
Add a traditional cell cutoff following both the cellranger methology and and by finding the inflection point

### CODE REVIEW

**Comment by barkasn** [comment]
retest this please

**Comment by barkasn** [comment]
retest this please

**Comment by barkasn** [comment]
retest this please

**Comment by nikellepetrillo** [comment]
@kishorikonwar do you know if we still want to merge in this work?

**Comment by kbergin** [comment]
We will revisit this in the future.

**Pull request closed without merging**
