### PR TITLE
Adding snyk check to this repo

### PR DESCRIPTION
**Pull request by rhiananthony**
### Purpose
Adding Snyk check
---
### Changes
Adding Snyk check to this repo

---
### PR Checklist
_Please ensure the following when opening a PR:_

- [ ] This PR added or updated tests.
- [ ] This PR updated docstrings or documentation.
- [ ] Let Jodi (**jodihir**) know when there is user-facing documentation updates needed!
- [ ] This PR applied the Mint style guide for WDL.
- [ ] This PR has no WDL linting errors reported by [miniwdl](https://github.com/chanzuckerberg/miniwdl)
- [ ] This PR considered generalizability beyond our own use case.

---
### Follow-up Discussions
_Please append follow-up discussions and issues during the review process below:_

- No follow-up discussions.

### CODE REVIEW

**Comment by samanehsan** [comment]
Do you know why the badge shows `unresponsive` instead of a number here @rhiananthony? 

Screen Shot 2019-03-26 at 11 40 02 AM

**Comment by samanehsan** [comment]
Also what do you think about moving the badge into the readme for the `cellranger` docker image? https://github.com/HumanCellAtlas/skylab/blob/master/docker/cellranger/README.md

Or maybe change the label?

**Comment by rexwangcc** [comment]
Interesting 🤔 It works for me: 
Screen Shot 2019-03-26 at 11 43 02 AM

**Comment by samanehsan** [comment]
Oh that's what I see now too @rexwangc! Nevermind!

**Pull request merged**
